In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
from tabulate import tabulate
df=pd.read_csv(r"/content/drive/MyDrive/Acorn/Project/공공자전거_대여소_정보(22.12월 기준).csv")
df_rental=pd.read_csv(r"/content/drive/MyDrive/Acorn/Project/강남대여소__2020.csv")
df_weather=pd.read_csv(r"/content/drive/MyDrive/Acorn/Project/train_weather_processed.csv")
df_air=pd.read_csv(r"/content/drive/MyDrive/Acorn/Project/train_air_processed.csv")
df_people=pd.read_csv(r"/content/drive/MyDrive/Acorn/Project/train_people_processed.csv")

In [3]:
print('대여소 정보 22 12월 기준')
print(tabulate(df.head(3), headers='keys', tablefmt='psql', showindex=True))
print()
print('강남대여소 20')
print(tabulate(df_rental.head(3), headers='keys', tablefmt='psql', showindex=True))
print()
print('강남대여소 공기오염도')
print(tabulate(df_air.head(3), headers='keys', tablefmt='psql', showindex=True))
print()
print('유동인구')
print(tabulate(df_people.head(3), headers='keys', tablefmt='psql', showindex=True))
print()

대여소 정보 22 12월 기준
+----+--------------+---------------------+----------+------------------------------------------------------+---------+---------+------------+-----------------+----------------+------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+
|    |   대여소번호 | 보관소(대여소)명    | 자치구   | 상세주소                                             |    위도 |    경도 | 설치시기   |   거치대수(LCD) |   거치대수(QR) | 운영방식   |   Unnamed: 10 |   Unnamed: 11 |   Unnamed: 12 |   Unnamed: 13 |   Unnamed: 14 |   Unnamed: 15 |   Unnamed: 16 |   Unnamed: 17 |   Unnamed: 18 |
|----+--------------+---------------------+----------+------------------------------------------------------+---------+---------+------------+-----------------+----------------+------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------|
|  0 |          301 | 경복궁역 7번출구 앞 | 종로구   | 서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞 | 37.5758 | 126.971 | 2015-10-07 |              20 |            nan | LCD        |           nan |           nan |           nan |           nan |           nan |           nan |           nan |           nan |           nan |
|  1 |          302 | 경복궁역 4번출구 뒤 | 종로구   | 서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤 | 37.5759 | 126.974 | 2015-10-07 |             nan |             12 | QR         |           nan |           nan |           nan |           nan |           nan |           nan |           nan |           nan |           nan |
|  2 |          303 | 광화문역 1번출구 앞 | 종로구   | 서울특별시 종로구 세종대로 지하189 세종로공원        | 37.5718 | 126.975 | 2015-10-07 |             nan |              8 | QR         |           nan |           nan |           nan |           nan |           nan |           nan |           nan |           nan |           nan |
+----+--------------+---------------------+----------+------------------------------------------------------+---------+---------+------------+-----------------+----------------+------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+

강남대여소 20
+----+------------------------+------------+----------+------------+
|    | 대여 대여소명          | 날짜       |   시간대 |   이용건수 |
|----+------------------------+------------+----------+------------|
|  0 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        0 |          1 |
|  1 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        1 |          0 |
|  2 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        2 |          0 |
+----+------------------------+------------+----------+------------+

강남대여소 공기오염도
+----+-------------+---------------+------------+----------+-------------+------------+
|    |    측정일시 |   측정소 코드 |   측정항목 |   평균값 |      측정일 |   측정시간 |
|----+-------------+---------------+------------+----------+-------------+------------|
|  0 | 2.02001e+09 |           123 |          9 |       24 | 2.02001e+07 |        nan |
|  1 | 2.02001e+09 |           123 |          9 |       21 | 2.02001e+07 |          1 |
|  2 | 2.02001e+09 |           123 |          9 |       15 | 2.02001e+07 |          2 |
+----+-------------+---------------+------------+----------+-------------+------------+

유동인구
+----+------------+--------------+----------------+--------------+-----------------------------------+
|    |   기준일ID |   시간대구분 |   총생활인구수 |   대여소번호 | 보관소(대여소)명                  |
|----+------------+--------------+----------------+--------------+-----------------------------------|
|  0 |   20200101 |            0 |        8313.59 |         2358 | 구룡초사거리 (현대아파트10동 앞 ) |
|  1 |   20200101 |            0 |       25512.9  |         2325 | 대치삼성아파트 앞 교차로          |
|  2 |   20200101 |            0 |       46405.6  |         2343 | 세곡사거리 대왕파출소 앞          |
+----+------------+--------------+----------------+--------------+-----------------------------------+

# 20-21 강남대여소에 대여소코드 넣기

In [4]:
print(tabulate(df.head(3), headers='keys', tablefmt='psql', showindex=True))
print()
print(df.columns)
df=df.drop(columns=['자치구', '상세주소', '위도', '경도', '설치시기', '거치대수(LCD)',
       '거치대수(QR)', '운영방식', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18'])

print(tabulate(df.head(3), headers='keys', tablefmt='psql', showindex=True))

+----+--------------+---------------------+----------+------------------------------------------------------+---------+---------+------------+-----------------+----------------+------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+
|    |   대여소번호 | 보관소(대여소)명    | 자치구   | 상세주소                                             |    위도 |    경도 | 설치시기   |   거치대수(LCD) |   거치대수(QR) | 운영방식   |   Unnamed: 10 |   Unnamed: 11 |   Unnamed: 12 |   Unnamed: 13 |   Unnamed: 14 |   Unnamed: 15 |   Unnamed: 16 |   Unnamed: 17 |   Unnamed: 18 |
|----+--------------+---------------------+----------+------------------------------------------------------+---------+---------+------------+-----------------+----------------+------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------|
|  0 |          301 | 경복궁역 7번출구 앞 | 종로구   | 서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞 | 37.5758 | 126.971 | 2015-10-07 |              20 |            nan | LCD        |           nan |           nan |           nan |           nan |           nan |           nan |           nan |           nan |           nan |
|  1 |          302 | 경복궁역 4번출구 뒤 | 종로구   | 서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤 | 37.5759 | 126.974 | 2015-10-07 |             nan |             12 | QR         |           nan |           nan |           nan |           nan |           nan |           nan |           nan |           nan |           nan |
|  2 |          303 | 광화문역 1번출구 앞 | 종로구   | 서울특별시 종로구 세종대로 지하189 세종로공원        | 37.5718 | 126.975 | 2015-10-07 |             nan |              8 | QR         |           nan |           nan |           nan |           nan |           nan |           nan |           nan |           nan |           nan |
+----+--------------+---------------------+----------+------------------------------------------------------+---------+---------+------------+-----------------+----------------+------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+

Index(['대여소번호', '보관소(대여소)명', '자치구', '상세주소', '위도', '경도', '설치시기', '거치대수(LCD)',
       '거치대수(QR)', '운영방식', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18'],
      dtype='object')
+----+--------------+---------------------+
|    |   대여소번호 | 보관소(대여소)명    |
|----+--------------+---------------------|
|  0 |          301 | 경복궁역 7번출구 앞 |
|  1 |          302 | 경복궁역 4번출구 뒤 |
|  2 |          303 | 광화문역 1번출구 앞 |
+----+--------------+---------------------+

In [5]:
df = df.rename(columns={'보관소(대여소)명': '대여 대여소명'})

print(tabulate(df.head(3), headers='keys', tablefmt='psql', showindex=True))

+----+--------------+---------------------+
|    |   대여소번호 | 대여 대여소명       |
|----+--------------+---------------------|
|  0 |          301 | 경복궁역 7번출구 앞 |
|  1 |          302 | 경복궁역 4번출구 뒤 |
|  2 |          303 | 광화문역 1번출구 앞 |
+----+--------------+---------------------+


# 대여소+강수량 데이터

In [6]:
# df 데이터프레임의 '대여 대여소명' 열의 앞 뒤 공백 제거
df['대여 대여소명'] = df['대여 대여소명'].str.strip()
df_rental['대여 대여소명'] = df_rental['대여 대여소명'].str.strip()

# df_rental과 df 테이블을 대여 대여소명을 기준으로 조인
df_rental = pd.merge(df_rental, df, on='대여 대여소명', how='left')

print(tabulate(df_rental.head(50), headers='keys', tablefmt='psql', showindex=True))

+----+------------------------+------------+----------+------------+--------------+
|    | 대여 대여소명          | 날짜       |   시간대 |   이용건수 |   대여소번호 |
|----+------------------------+------------+----------+------------+--------------|
|  0 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        0 |          1 |         2335 |
|  1 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        1 |          0 |         2335 |
|  2 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        2 |          0 |         2335 |
|  3 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        3 |          0 |         2335 |
|  4 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        4 |          0 |         2335 |
|  5 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        5 |          0 |         2335 |
|  6 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        6 |          0 |         2335 |
|  7 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        7 |          1 |         2335 |
|  8 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        8 |          0 |         2335 |
|  9 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        9 |          0 |         2335 |
| 10 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       10 |          0 |         2335 |
| 11 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       11 |          1 |         2335 |
| 12 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       12 |          2 |         2335 |
| 13 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       13 |          0 |         2335 |
| 14 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       14 |          0 |         2335 |
| 15 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       15 |          2 |         2335 |
| 16 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       16 |          1 |         2335 |
| 17 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       17 |          0 |         2335 |
| 18 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       18 |          2 |         2335 |
| 19 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       19 |          0 |         2335 |
| 20 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       20 |          0 |         2335 |
| 21 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       21 |          0 |         2335 |
| 22 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       22 |          0 |         2335 |
| 23 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       23 |          0 |         2335 |
| 24 | 3호선 매봉역 3번출구앞 | 2020-01-02 |        0 |          0 |         2335 |
| 25 | 3호선 매봉역 3번출구앞 | 2020-01-02 |        1 |          0 |         2335 |
| 26 | 3호선 매봉역 3번출구앞 | 2020-01-02 |        2 |          0 |         2335 |
| 27 | 3호선 매봉역 3번출구앞 | 2020-01-02 |        3 |          0 |         2335 |
| 28 | 3호선 매봉역 3번출구앞 | 2020-01-02 |        4 |          0 |         2335 |
| 29 | 3호선 매봉역 3번출구앞 | 2020-01-02 |        5 |          0 |         2335 |
| 30 | 3호선 매봉역 3번출구앞 | 2020-01-02 |        6 |          1 |         2335 |
| 31 | 3호선 매봉역 3번출구앞 | 2020-01-02 |        7 |          0 |         2335 |
| 32 | 3호선 매봉역 3번출구앞 | 2020-01-02 |        8 |          1 |         2335 |
| 33 | 3호선 매봉역 3번출구앞 | 2020-01-02 |        9 |          0 |         2335 |
| 34 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       10 |          1 |         2335 |
| 35 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       11 |          1 |         2335 |
| 36 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       12 |          0 |         2335 |
| 37 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       13 |          0 |         2335 |
| 38 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       14 |          1 |         2335 |
| 39 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       15 |          5 |         2335 |
| 40 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       16 |          1 |         2335 |
| 41 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       17 |          0 |         2335 |
| 42 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       18 |          0 |         2335 |
| 43 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       19 |          0 |         2335 |
| 44 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       20 |          1 |         2335 |
| 45 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       21 |          2 |         2335 |
| 46 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       22 |          2 |         2335 |
| 47 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       23 |          1 |         2335 |
| 48 | 3호선 매봉역 3번출구앞 | 2020-01-03 |        0 |          2 |         2335 |
| 49 | 3호선 매봉역 3번출구앞 | 2020-01-03 |        1 |          1 |         2335 |
+----+------------------------+------------+----------+------------+--------------+

In [7]:
print(tabulate(df_rental.tail(50), headers='keys', tablefmt='psql', showindex=True))

+--------+-----------------+------------+----------+------------+--------------+
|        | 대여 대여소명   | 날짜       |   시간대 |   이용건수 |   대여소번호 |
|--------+-----------------+------------+----------+------------+--------------|
| 860243 | 크린랩 본사     | 2020-12-29 |       22 |          0 |         2386 |
| 860244 | 크린랩 본사     | 2020-12-29 |       23 |          0 |         2386 |
| 860245 | 크린랩 본사     | 2020-12-30 |        0 |          0 |         2386 |
| 860246 | 크린랩 본사     | 2020-12-30 |        1 |          0 |         2386 |
| 860247 | 크린랩 본사     | 2020-12-30 |        2 |          0 |         2386 |
| 860248 | 크린랩 본사     | 2020-12-30 |        3 |          0 |         2386 |
| 860249 | 크린랩 본사     | 2020-12-30 |        4 |          0 |         2386 |
| 860250 | 크린랩 본사     | 2020-12-30 |        5 |          0 |         2386 |
| 860251 | 크린랩 본사     | 2020-12-30 |        6 |          0 |         2386 |
| 860252 | 크린랩 본사     | 2020-12-30 |        7 |          0 |         2386 |
| 860253 | 크린랩 본사     | 2020-12-30 |        8 |          0 |         2386 |
| 860254 | 크린랩 본사     | 2020-12-30 |        9 |          0 |         2386 |
| 860255 | 크린랩 본사     | 2020-12-30 |       10 |          0 |         2386 |
| 860256 | 크린랩 본사     | 2020-12-30 |       11 |          0 |         2386 |
| 860257 | 크린랩 본사     | 2020-12-30 |       12 |          0 |         2386 |
| 860258 | 크린랩 본사     | 2020-12-30 |       13 |          0 |         2386 |
| 860259 | 크린랩 본사     | 2020-12-30 |       14 |          0 |         2386 |
| 860260 | 크린랩 본사     | 2020-12-30 |       15 |          0 |         2386 |
| 860261 | 크린랩 본사     | 2020-12-30 |       16 |          0 |         2386 |
| 860262 | 크린랩 본사     | 2020-12-30 |       17 |          0 |         2386 |
| 860263 | 크린랩 본사     | 2020-12-30 |       18 |          0 |         2386 |
| 860264 | 크린랩 본사     | 2020-12-30 |       19 |          0 |         2386 |
| 860265 | 크린랩 본사     | 2020-12-30 |       20 |          0 |         2386 |
| 860266 | 크린랩 본사     | 2020-12-30 |       21 |          0 |         2386 |
| 860267 | 크린랩 본사     | 2020-12-30 |       22 |          0 |         2386 |
| 860268 | 크린랩 본사     | 2020-12-30 |       23 |          0 |         2386 |
| 860269 | 크린랩 본사     | 2020-12-31 |        0 |          0 |         2386 |
| 860270 | 크린랩 본사     | 2020-12-31 |        1 |          0 |         2386 |
| 860271 | 크린랩 본사     | 2020-12-31 |        2 |          0 |         2386 |
| 860272 | 크린랩 본사     | 2020-12-31 |        3 |          0 |         2386 |
| 860273 | 크린랩 본사     | 2020-12-31 |        4 |          0 |         2386 |
| 860274 | 크린랩 본사     | 2020-12-31 |        5 |          0 |         2386 |
| 860275 | 크린랩 본사     | 2020-12-31 |        6 |          0 |         2386 |
| 860276 | 크린랩 본사     | 2020-12-31 |        7 |          0 |         2386 |
| 860277 | 크린랩 본사     | 2020-12-31 |        8 |          0 |         2386 |
| 860278 | 크린랩 본사     | 2020-12-31 |        9 |          0 |         2386 |
| 860279 | 크린랩 본사     | 2020-12-31 |       10 |          0 |         2386 |
| 860280 | 크린랩 본사     | 2020-12-31 |       11 |          0 |         2386 |
| 860281 | 크린랩 본사     | 2020-12-31 |       12 |          0 |         2386 |
| 860282 | 크린랩 본사     | 2020-12-31 |       13 |          0 |         2386 |
| 860283 | 크린랩 본사     | 2020-12-31 |       14 |          0 |         2386 |
| 860284 | 크린랩 본사     | 2020-12-31 |       15 |          0 |         2386 |
| 860285 | 크린랩 본사     | 2020-12-31 |       16 |          0 |         2386 |
| 860286 | 크린랩 본사     | 2020-12-31 |       17 |          0 |         2386 |
| 860287 | 크린랩 본사     | 2020-12-31 |       18 |          0 |         2386 |
| 860288 | 크린랩 본사     | 2020-12-31 |       19 |          0 |         2386 |
| 860289 | 크린랩 본사     | 2020-12-31 |       20 |          0 |         2386 |
| 860290 | 크린랩 본사     | 2020-12-31 |       21 |          0 |         2386 |
| 860291 | 크린랩 본사     | 2020-12-31 |       22 |          0 |         2386 |
| 860292 | 크린랩 본사     | 2020-12-31 |       23 |          0 |         2386 |
+--------+-----------------+------------+----------+------------+--------------+

In [8]:
print(df_weather.columns)
print()

# '일시' 열의 이름을 '날짜'로 변경
df_weather = df_weather.rename(columns={'일시': '날짜'})

# 결과 출력
print(tabulate(df_weather.head(3), headers='keys', tablefmt='psql', showindex=True))

Index(['지점', '지점명', '일시', '평균기온(°C)', '일강수량(mm)'], dtype='object')

+----+--------+----------+------------+----------------+----------------+
|    |   지점 | 지점명   | 날짜       |   평균기온(°C) | 일강수량(mm)   |
|----+--------+----------+------------+----------------+----------------|
|  0 |    108 | 서울     | 2020-01-01 |           -2.2 | 비옴           |
|  1 |    108 | 서울     | 2020-01-02 |            1   | 비안옴         |
|  2 |    108 | 서울     | 2020-01-03 |           -0.1 | 비안옴         |
+----+--------+----------+------------+----------------+----------------+

In [9]:
# 날짜를 기준으로 두 데이터프레임 병합
merged_df = pd.merge(df_rental, df_weather, on='날짜', how='left')

# 필요한 경우 칼럼명을 조정하여 원하는 형식으로 만들기
merged_df.rename(columns={'일강수량(mm)': '날씨'}, inplace=True)

# 결과 출력
print(merged_df.columns)
print()

print(tabulate(merged_df.head(3), headers='keys', tablefmt='psql', showindex=True))
print()

# 합친 데이터프레임에서 필요한 칼럼만 가져오기
selected_columns = ['대여소번호','대여 대여소명', '날짜', '시간대', '날씨',  '평균기온(°C)']
subset_df = merged_df[selected_columns]
print(tabulate(subset_df.head(3), headers='keys', tablefmt='psql', showindex=True))
print(subset_df.shape)

Index(['대여 대여소명', '날짜', '시간대', '이용건수', '대여소번호', '지점', '지점명', '평균기온(°C)', '날씨'], dtype='object')

+----+------------------------+------------+----------+------------+--------------+--------+----------+----------------+--------+
|    | 대여 대여소명          | 날짜       |   시간대 |   이용건수 |   대여소번호 |   지점 | 지점명   |   평균기온(°C) | 날씨   |
|----+------------------------+------------+----------+------------+--------------+--------+----------+----------------+--------|
|  0 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        0 |          1 |         2335 |    108 | 서울     |           -2.2 | 비옴   |
|  1 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        1 |          0 |         2335 |    108 | 서울     |           -2.2 | 비옴   |
|  2 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        2 |          0 |         2335 |    108 | 서울     |           -2.2 | 비옴   |
+----+------------------------+------------+----------+------------+--------------+--------+----------+----------------+--------+

+----+--------------+------------------------+------------+----------+--------+----------------+
|    |   대여소번호 | 대여 대여소명          | 날짜       |   시간대 | 날씨   |   평균기온(°C) |
|----+--------------+------------------------+------------+----------+--------+----------------|
|  0 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        0 | 비옴   |           -2.2 |
|  1 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        1 | 비옴   |           -2.2 |
|  2 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        2 | 비옴   |           -2.2 |
+----+--------------+------------------------+------------+----------+--------+----------------+
(860293, 6)

# 대여소+강수량+(공기오염도 - 평균값을 넣기)

In [10]:
print(df_air.columns)
print(tabulate(df_air.head(3), headers='keys', tablefmt='psql', showindex=True))

Index(['측정일시', '측정소 코드', '측정항목', '평균값', '측정일', '측정시간'], dtype='object')
+----+-------------+---------------+------------+----------+-------------+------------+
|    |    측정일시 |   측정소 코드 |   측정항목 |   평균값 |      측정일 |   측정시간 |
|----+-------------+---------------+------------+----------+-------------+------------|
|  0 | 2.02001e+09 |           123 |          9 |       24 | 2.02001e+07 |        nan |
|  1 | 2.02001e+09 |           123 |          9 |       21 | 2.02001e+07 |          1 |
|  2 | 2.02001e+09 |           123 |          9 |       15 | 2.02001e+07 |          2 |
+----+-------------+---------------+------------+----------+-------------+------------+

In [11]:
# '일시' 열의 이름을 '날짜'로 변경
df_air = df_air.rename(columns={'측정일': '날짜'})

# 결과 출력
print(tabulate(df_air.head(3), headers='keys', tablefmt='psql', showindex=True))

+----+-------------+---------------+------------+----------+-------------+------------+
|    |    측정일시 |   측정소 코드 |   측정항목 |   평균값 |        날짜 |   측정시간 |
|----+-------------+---------------+------------+----------+-------------+------------|
|  0 | 2.02001e+09 |           123 |          9 |       24 | 2.02001e+07 |        nan |
|  1 | 2.02001e+09 |           123 |          9 |       21 | 2.02001e+07 |          1 |
|  2 | 2.02001e+09 |           123 |          9 |       15 | 2.02001e+07 |          2 |
+----+-------------+---------------+------------+----------+-------------+------------+

In [12]:
# 날짜 형식 변경
df_air['날짜'] = pd.to_datetime(df_air['날짜'], format='%Y%m%d')

# 날짜를 원하는 형식으로 다시 문자열로 변환
df_air['날짜'] = df_air['날짜'].dt.strftime('%Y-%m-%d')

#측정시간 NaN값 0으로
df_air['측정시간'] = df_air['측정시간'].fillna(0)
print(tabulate(df_air.head(3), headers='keys', tablefmt='psql', showindex=True))

+----+------------+---------------+------------+----------+------------+------------+
|    |   측정일시 |   측정소 코드 |   측정항목 |   평균값 | 날짜       |   측정시간 |
|----+------------+---------------+------------+----------+------------+------------|
|  0 | 2020010100 |           123 |          9 |       24 | 2020-01-01 |          0 |
|  1 | 2020010101 |           123 |          9 |       21 | 2020-01-01 |          1 |
|  2 | 2020010102 |           123 |          9 |       15 | 2020-01-01 |          2 |
+----+------------+---------------+------------+----------+------------+------------+

In [13]:
# df_air 칼럼의 측정시간 값과 일치하는 것을 기준으로 두 데이터프레임을 날짜를 기준으로 병합
merged_df = pd.merge(subset_df, df_air, left_on=['날짜', '시간대'], right_on=['날짜', '측정시간'], how='left')

# 필요한 경우 칼럼명을 조정하여 원하는 형식으로 만들기
merged_df.rename(columns={'평균값': 'Pm2.5'}, inplace=True)

# 결과 출력
print(tabulate(merged_df.head(3), headers='keys', tablefmt='psql', showindex=True))

+----+--------------+------------------------+------------+----------+--------+----------------+------------+---------------+------------+---------+------------+
|    |   대여소번호 | 대여 대여소명          | 날짜       |   시간대 | 날씨   |   평균기온(°C) |   측정일시 |   측정소 코드 |   측정항목 |   Pm2.5 |   측정시간 |
|----+--------------+------------------------+------------+----------+--------+----------------+------------+---------------+------------+---------+------------|
|  0 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        0 | 비옴   |           -2.2 | 2020010100 |           123 |          9 |      24 |          0 |
|  1 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        1 | 비옴   |           -2.2 | 2020010101 |           123 |          9 |      21 |          1 |
|  2 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        2 | 비옴   |           -2.2 | 2020010102 |           123 |          9 |      15 |          2 |
+----+--------------+------------------------+------------+----------+--------+----------------+------------+---------------+------------+---------+------------+

In [14]:
# 제외할 열 목록
excluded_columns = ['측정일시', '측정소 코드', '측정항목', '측정시간']

# 제외한 열만 선택하여 새로운 데이터프레임 생성
final_df = merged_df.drop(columns=excluded_columns)
print(tabulate(final_df.head(3), headers='keys', tablefmt='psql', showindex=True))

+----+--------------+------------------------+------------+----------+--------+----------------+---------+
|    |   대여소번호 | 대여 대여소명          | 날짜       |   시간대 | 날씨   |   평균기온(°C) |   Pm2.5 |
|----+--------------+------------------------+------------+----------+--------+----------------+---------|
|  0 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        0 | 비옴   |           -2.2 |      24 |
|  1 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        1 | 비옴   |           -2.2 |      21 |
|  2 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        2 | 비옴   |           -2.2 |      15 |
+----+--------------+------------------------+------------+----------+--------+----------------+---------+

# 유동인구 추가하기

In [15]:
print(df_people.columns)
print(tabulate(df_people.head(3), headers='keys', tablefmt='psql', showindex=True))

Index(['기준일ID', '시간대구분', '총생활인구수', '대여소번호', '보관소(대여소)명'], dtype='object')
+----+------------+--------------+----------------+--------------+-----------------------------------+
|    |   기준일ID |   시간대구분 |   총생활인구수 |   대여소번호 | 보관소(대여소)명                  |
|----+------------+--------------+----------------+--------------+-----------------------------------|
|  0 |   20200101 |            0 |        8313.59 |         2358 | 구룡초사거리 (현대아파트10동 앞 ) |
|  1 |   20200101 |            0 |       25512.9  |         2325 | 대치삼성아파트 앞 교차로          |
|  2 |   20200101 |            0 |       46405.6  |         2343 | 세곡사거리 대왕파출소 앞          |
+----+------------+--------------+----------------+--------------+-----------------------------------+

In [16]:
# '보관소(대여소)명' 열의 이름을 '대여 대여소명'로 변경
df_people = df_people.rename(columns={'보관소(대여소)명': '대여 대여소명','기준일ID':'날짜','시간대구분':'시간대','총생활인구수':'유동인구(명)'})

# '유동인구(명)' 칼럼의 데이터를 int 타입으로 변환
df_people['유동인구(명)'] = df_people['유동인구(명)'].astype(int)

print(tabulate(df_people.head(3), headers='keys', tablefmt='psql', showindex=True))

+----+----------+----------+----------------+--------------+-----------------------------------+
|    |     날짜 |   시간대 |   유동인구(명) |   대여소번호 | 대여 대여소명                     |
|----+----------+----------+----------------+--------------+-----------------------------------|
|  0 | 20200101 |        0 |           8313 |         2358 | 구룡초사거리 (현대아파트10동 앞 ) |
|  1 | 20200101 |        0 |          25512 |         2325 | 대치삼성아파트 앞 교차로          |
|  2 | 20200101 |        0 |          46405 |         2343 | 세곡사거리 대왕파출소 앞          |
+----+----------+----------+----------------+--------------+-----------------------------------+

In [17]:
print(tabulate(final_df.head(3), headers='keys', tablefmt='psql', showindex=True))

+----+--------------+------------------------+------------+----------+--------+----------------+---------+
|    |   대여소번호 | 대여 대여소명          | 날짜       |   시간대 | 날씨   |   평균기온(°C) |   Pm2.5 |
|----+--------------+------------------------+------------+----------+--------+----------------+---------|
|  0 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        0 | 비옴   |           -2.2 |      24 |
|  1 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        1 | 비옴   |           -2.2 |      21 |
|  2 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        2 | 비옴   |           -2.2 |      15 |
+----+--------------+------------------------+------------+----------+--------+----------------+---------+

In [18]:
# 날짜 형식 변경
df_people['날짜'] = pd.to_datetime(df_people['날짜'], format='%Y%m%d')

# 날짜를 원하는 형식으로 다시 문자열로 변환
df_people['날짜'] = df_people['날짜'].dt.strftime('%Y-%m-%d')

# df 데이터프레임의 '대여 대여소명' 열의 앞 뒤 공백 제거
final_df['대여 대여소명'] = final_df['대여 대여소명'].str.strip()
df_people['대여 대여소명'] = df_rental['대여 대여소명'].str.strip()

# df_people 칼럼의 측정시간 값과 일치하는 것을 기준으로 두 데이터프레임을 날짜를 기준으로 병합
final_df = pd.merge(final_df, df_people, left_on=['날짜', '시간대','대여소번호'], right_on=['날짜', '시간대','대여소번호'], how='left')

print(final_df.shape)
print(tabulate(final_df.head(), headers='keys', tablefmt='psql', showindex=True))

(860293, 9)
+----+--------------+------------------------+------------+----------+--------+----------------+---------+----------------+------------------------+
|    |   대여소번호 | 대여 대여소명_x        | 날짜       |   시간대 | 날씨   |   평균기온(°C) |   Pm2.5 |   유동인구(명) | 대여 대여소명_y        |
|----+--------------+------------------------+------------+----------+--------+----------------+---------+----------------+------------------------|
|  0 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        0 | 비옴   |           -2.2 |      24 |          27965 | 3호선 매봉역 3번출구앞 |
|  1 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        1 | 비옴   |           -2.2 |      21 |          28337 | 3호선 매봉역 3번출구앞 |
|  2 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        2 | 비옴   |           -2.2 |      15 |          28410 | 3호선 매봉역 3번출구앞 |
|  3 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        3 | 비옴   |           -2.2 |      12 |          28422 | 3호선 매봉역 3번출구앞 |
|  4 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        4 | 비옴   |           -2.2 |      15 |          28278 | 3호선 매봉역 3번출구앞 |
+----+--------------+------------------------+------------+----------+--------+----------------+---------+----------------+------------------------+

In [19]:
# 제외한 열만 선택하여 새로운 데이터프레임 생성
final_df = final_df.drop(columns='대여 대여소명_y')

# '보관소(대여소)명' 열의 이름을 '대여 대여소명'로 변경
final_df = final_df.rename(columns={'대여 대여소명_x': '대여 대여소명'})

In [20]:
print(tabulate(final_df.head(50), headers='keys', tablefmt='psql', showindex=True))
print(tabulate(final_df.tail(50), headers='keys', tablefmt='psql', showindex=True))

+----+--------------+------------------------+------------+----------+--------+----------------+---------+----------------+
|    |   대여소번호 | 대여 대여소명          | 날짜       |   시간대 | 날씨   |   평균기온(°C) |   Pm2.5 |   유동인구(명) |
|----+--------------+------------------------+------------+----------+--------+----------------+---------+----------------|
|  0 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        0 | 비옴   |           -2.2 |      24 |          27965 |
|  1 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        1 | 비옴   |           -2.2 |      21 |          28337 |
|  2 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        2 | 비옴   |           -2.2 |      15 |          28410 |
|  3 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        3 | 비옴   |           -2.2 |      12 |          28422 |
|  4 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        4 | 비옴   |           -2.2 |      15 |          28278 |
|  5 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        5 | 비옴   |           -2.2 |      14 |          28477 |
|  6 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        6 | 비옴   |           -2.2 |      16 |          28548 |
|  7 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        7 | 비옴   |           -2.2 |      16 |          28447 |
|  8 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        8 | 비옴   |           -2.2 |      18 |          28136 |
|  9 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |        9 | 비옴   |           -2.2 |      18 |          27690 |
| 10 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       10 | 비옴   |           -2.2 |      20 |          27871 |
| 11 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       11 | 비옴   |           -2.2 |      21 |          27180 |
| 12 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       12 | 비옴   |           -2.2 |      23 |          27222 |
| 13 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       13 | 비옴   |           -2.2 |      25 |          27131 |
| 14 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       14 | 비옴   |           -2.2 |      29 |          26904 |
| 15 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       15 | 비옴   |           -2.2 |      26 |          26467 |
| 16 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       16 | 비옴   |           -2.2 |      25 |          26477 |
| 17 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       17 | 비옴   |           -2.2 |      27 |          26678 |
| 18 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       18 | 비옴   |           -2.2 |      28 |          26705 |
| 19 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       19 | 비옴   |           -2.2 |      31 |          26522 |
| 20 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       20 | 비옴   |           -2.2 |      31 |          26716 |
| 21 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       21 | 비옴   |           -2.2 |      32 |          26814 |
| 22 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       22 | 비옴   |           -2.2 |      34 |          27532 |
| 23 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-01 |       23 | 비옴   |           -2.2 |      32 |          29365 |
| 24 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |        0 | 비안옴 |            1   |      32 |          29325 |
| 25 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |        1 | 비안옴 |            1   |      34 |          29113 |
| 26 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |        2 | 비안옴 |            1   |      33 |          29010 |
| 27 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |        3 | 비안옴 |            1   |      32 |          29058 |
| 28 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |        4 | 비안옴 |            1   |      33 |          29014 |
| 29 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |        5 | 비안옴 |            1   |      32 |          29137 |
| 30 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |        6 | 비안옴 |            1   |      34 |          29372 |
| 31 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |        7 | 비안옴 |            1   |      34 |          29857 |
| 32 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |        8 | 비안옴 |            1   |      37 |          31648 |
| 33 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |        9 | 비안옴 |            1   |      39 |          32631 |
| 34 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       10 | 비안옴 |            1   |      46 |          33411 |
| 35 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       11 | 비안옴 |            1   |      47 |          33477 |
| 36 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       12 | 비안옴 |            1   |      52 |          33293 |
| 37 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       13 | 비안옴 |            1   |      51 |          33064 |
| 38 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       14 | 비안옴 |            1   |      49 |          32710 |
| 39 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       15 | 비안옴 |            1   |      46 |          32762 |
| 40 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       16 | 비안옴 |            1   |      52 |          32050 |
| 41 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       17 | 비안옴 |            1   |      48 |          31723 |
| 42 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       18 | 비안옴 |            1   |      50 |          30779 |
| 43 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       19 | 비안옴 |            1   |      50 |          28754 |
| 44 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       20 | 비안옴 |            1   |      52 |          27882 |
| 45 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       21 | 비안옴 |            1   |      51 |          27908 |
| 46 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       22 | 비안옴 |            1   |      53 |          27622 |
| 47 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-02 |       23 | 비안옴 |            1   |      51 |          29835 |
| 48 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-03 |        0 | 비안옴 |           -0.1 |      52 |          29545 |
| 49 |         2335 | 3호선 매봉역 3번출구앞 | 2020-01-03 |        1 | 비안옴 |           -0.1 |      52 |          29652 |
+----+--------------+------------------------+------------+----------+--------+----------------+---------+----------------+
+--------+--------------+-----------------+------------+----------+--------+----------------+---------+----------------+
|        |   대여소번호 | 대여 대여소명   | 날짜       |   시간대 | 날씨   |   평균기온(°C) |   Pm2.5 |   유동인구(명) |
|--------+--------------+-----------------+------------+----------+--------+----------------+---------+----------------|
| 860243 |         2386 | 크린랩 본사     | 2020-12-29 |       22 | 비옴   |            0.1 |      30 |          34212 |
| 860244 |         2386 | 크린랩 본사     | 2020-12-29 |       23 | 비옴   |            0.1 |      22 |          32451 |
| 860245 |         2386 | 크린랩 본사     | 2020-12-30 |        0 | 비안옴 |          -10.9 |      21 |          32030 |
| 860246 |         2386 | 크린랩 본사     | 2020-12-30 |        1 | 비안옴 |          -10.9 |      26 |          31480 |
| 860247 |         2386 | 크린랩 본사     | 2020-12-30 |        2 | 비안옴 |          -10.9 |      23 |          31370 |
| 860248 |         2386 | 크린랩 본사     | 2020-12-30 |        3 | 비안옴 |          -10.9 |      23 |          31294 |
| 860249 |         2386 | 크린랩 본사     | 2020-12-30 |        4 | 비안옴 |          -10.9 |      17 |          31424 |
| 860250 |         2386 | 크린랩 본사     | 2020-12-30 |        5 | 비안옴 |          -10.9 |      19 |          31472 |
| 860251 |         2386 | 크린랩 본사     | 2020-12-30 |        6 | 비안옴 |          -10.9 |      16 |          32588 |
| 860252 |         2386 | 크린랩 본사     | 2020-12-30 |        7 | 비안옴 |          -10.9 |      13 |          35597 |
| 860253 |         2386 | 크린랩 본사     | 2020-12-30 |        8 | 비안옴 |          -10.9 |      10 |          44492 |
| 860254 |         2386 | 크린랩 본사     | 2020-12-30 |        9 | 비안옴 |          -10.9 |      13 |          52454 |
| 860255 |         2386 | 크린랩 본사     | 2020-12-30 |       10 | 비안옴 |          -10.9 |      13 |          55851 |
| 860256 |         2386 | 크린랩 본사     | 2020-12-30 |       11 | 비안옴 |          -10.9 |       7 |          59119 |
| 860257 |         2386 | 크린랩 본사     | 2020-12-30 |       12 | 비안옴 |          -10.9 |       8 |          60552 |
| 860258 |         2386 | 크린랩 본사     | 2020-12-30 |       13 | 비안옴 |          -10.9 |      12 |          61395 |
| 860259 |         2386 | 크린랩 본사     | 2020-12-30 |       14 | 비안옴 |          -10.9 |      13 |          61456 |
| 860260 |         2386 | 크린랩 본사     | 2020-12-30 |       15 | 비안옴 |          -10.9 |       9 |          60543 |
| 860261 |         2386 | 크린랩 본사     | 2020-12-30 |       16 | 비안옴 |          -10.9 |       7 |          59540 |
| 860262 |         2386 | 크린랩 본사     | 2020-12-30 |       17 | 비안옴 |          -10.9 |      12 |          57349 |
| 860263 |         2386 | 크린랩 본사     | 2020-12-30 |       18 | 비안옴 |          -10.9 |      13 |          51061 |
| 860264 |         2386 | 크린랩 본사     | 2020-12-30 |       19 | 비안옴 |          -10.9 |      11 |          44311 |
| 860265 |         2386 | 크린랩 본사     | 2020-12-30 |       20 | 비안옴 |          -10.9 |       9 |          40127 |
| 860266 |         2386 | 크린랩 본사     | 2020-12-30 |       21 | 비안옴 |          -10.9 |      12 |          36289 |
| 860267 |         2386 | 크린랩 본사     | 2020-12-30 |       22 | 비안옴 |          -10.9 |      14 |          34653 |
| 860268 |         2386 | 크린랩 본사     | 2020-12-30 |       23 | 비안옴 |          -10.9 |      10 |          33344 |
| 860269 |         2386 | 크린랩 본사     | 2020-12-31 |        0 | 비옴   |           -8.9 |       7 |          32314 |
| 860270 |         2386 | 크린랩 본사     | 2020-12-31 |        1 | 비옴   |           -8.9 |      10 |          32184 |
| 860271 |         2386 | 크린랩 본사     | 2020-12-31 |        2 | 비옴   |           -8.9 |      11 |          31894 |
| 860272 |         2386 | 크린랩 본사     | 2020-12-31 |        3 | 비옴   |           -8.9 |       8 |          31716 |
| 860273 |         2386 | 크린랩 본사     | 2020-12-31 |        4 | 비옴   |           -8.9 |       7 |          31856 |
| 860274 |         2386 | 크린랩 본사     | 2020-12-31 |        5 | 비옴   |           -8.9 |      12 |          31803 |
| 860275 |         2386 | 크린랩 본사     | 2020-12-31 |        6 | 비옴   |           -8.9 |      12 |          32833 |
| 860276 |         2386 | 크린랩 본사     | 2020-12-31 |        7 | 비옴   |           -8.9 |       9 |          34982 |
| 860277 |         2386 | 크린랩 본사     | 2020-12-31 |        8 | 비옴   |           -8.9 |       7 |          42399 |
| 860278 |         2386 | 크린랩 본사     | 2020-12-31 |        9 | 비옴   |           -8.9 |      10 |          48467 |
| 860279 |         2386 | 크린랩 본사     | 2020-12-31 |       10 | 비옴   |           -8.9 |       9 |          51905 |
| 860280 |         2386 | 크린랩 본사     | 2020-12-31 |       11 | 비옴   |           -8.9 |       4 |          54243 |
| 860281 |         2386 | 크린랩 본사     | 2020-12-31 |       12 | 비옴   |           -8.9 |       8 |          54624 |
| 860282 |         2386 | 크린랩 본사     | 2020-12-31 |       13 | 비옴   |           -8.9 |      15 |          54711 |
| 860283 |         2386 | 크린랩 본사     | 2020-12-31 |       14 | 비옴   |           -8.9 |      14 |          53406 |
| 860284 |         2386 | 크린랩 본사     | 2020-12-31 |       15 | 비옴   |           -8.9 |      11 |          51315 |
| 860285 |         2386 | 크린랩 본사     | 2020-12-31 |       16 | 비옴   |           -8.9 |      11 |          48634 |
| 860286 |         2386 | 크린랩 본사     | 2020-12-31 |       17 | 비옴   |           -8.9 |      19 |          44770 |
| 860287 |         2386 | 크린랩 본사     | 2020-12-31 |       18 | 비옴   |           -8.9 |      19 |          40356 |
| 860288 |         2386 | 크린랩 본사     | 2020-12-31 |       19 | 비옴   |           -8.9 |      14 |          36578 |
| 860289 |         2386 | 크린랩 본사     | 2020-12-31 |       20 | 비옴   |           -8.9 |      12 |          34802 |
| 860290 |         2386 | 크린랩 본사     | 2020-12-31 |       21 | 비옴   |           -8.9 |      18 |          32139 |
| 860291 |         2386 | 크린랩 본사     | 2020-12-31 |       22 | 비옴   |           -8.9 |      21 |          31222 |
| 860292 |         2386 | 크린랩 본사     | 2020-12-31 |       23 | 비옴   |           -8.9 |      15 |          30137 |
+--------+--------------+-----------------+------------+----------+--------+----------------+---------+----------------+

In [21]:
final_df.to_csv('df_final.csv', index=False)